# Generated by Django 3.0.5 on 2020-05-30 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('created', models.DateTimeField(blank=True)),
                ('modified', models.DateTimeField(blank=True)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='WalletAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Public identifier')),
                ('created', models.DateTimeField(blank=True)),
                ('wallet_action_type', models.CharField(choices=[('CREATED', 'Created'), ('DEPOSITED', 'Deposited'), ('WITHDRAWN', 'Withdrawn')], max_length=30)),
                ('delta', models.IntegerField(help_text='balance delta.')),
                ('reference', models.TextField(blank=True)),
                ('reference_type', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('NONE', 'None')], default='NONE', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('result_balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.OneToOneField(help_text='User who performed the action.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Action',
                'verbose_name_plural': 'Wallet Actions',
            },
        ),
    ]
