# Generated by Django 3.0.8 on 2020-07-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200718_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('check', 'Check')], default='savings', max_length=20),
        ),
    ]
