# Generated by Django 3.0.8 on 2020-08-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20200718_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_fee_amount',
            field=models.DecimalField(decimal_places=2, default=125, max_digits=12),
            preserve_default=False,
        ),
    ]
