class WalletActionType:
    WALLET_ACTION_TYPE_CREATED = 'CREATED'
    WALLET_ACTION_TYPE_DEPOSITED = 'DEPOSITED'
    WALLET_ACTION_TYPE_WITHDRAWN = 'WITHDRAWN'
    CHOICES = (
        (WALLET_ACTION_TYPE_CREATED, 'Created'),
        (WALLET_ACTION_TYPE_DEPOSITED, 'Deposited'),
        (WALLET_ACTION_TYPE_WITHDRAWN, 'Withdrawn'),
    )

class WalletReferenceType:
    REFERENCE_TYPE_BANK_TRANSFER = 'BANK_TRANSFER'
    REFERENCE_TYPE_CHECK = 'CHECK'
    REFERENCE_TYPE_CASH = 'CASH'
    REFERENCE_TYPE_NONE = 'NONE'
    CHOICES = (
        (REFERENCE_TYPE_BANK_TRANSFER, 'Bank Transfer'),
        (REFERENCE_TYPE_CHECK, 'Check'),
        (REFERENCE_TYPE_CASH, 'Cash'),
        (REFERENCE_TYPE_NONE, 'None'),
    )
