# Generated by Django 3.0.5 on 2020-05-14 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('partially fulfilled', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='unfulfilled', max_length=32)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('total_investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='campaign.Campaign')),
                ('invester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
