# Generated by Django 3.0.8 on 2020-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20200823_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='investment',
            name='shares',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
