# Generated by Django 3.0.5 on 2020-04-23 19:06

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20200423_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='image height'),
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='image width'),
        ),
        migrations.AlterField(
            model_name='campaignimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='placeholder1080x1080.png', height_field='height', upload_to='campaigns', verbose_name='image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='campaignimage',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='image PPOI'),
        ),
    ]
