# Generated by Django 3.0.5 on 2020-04-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20200423_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
