# Generated by Django 3.0.5 on 2020-04-23 09:05

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(default='placeholder540x540.png', upload_to='user-avatars'),
        ),
    ]
